version: '3.4'

services:
  julia:
    image: "julia"
    build:
      context: ./api
      dockerfile: Julia.Api/Dockerfile
    ports:
      - 8422:443
      - 6422:80
    volumes:
      - /c/Users/julol/.aspnet/https:/https
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=8422
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Julia.Api.pfx
    networks:
      - brenda-network
  sara:
    image: "sara"
    build:
      context: ./api
      dockerfile: Sara.Api/Dockerfile
    ports: 
      - 8421:443
    volumes:
      - /c/Users/julol/.aspnet/https:/https
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+
      - ASPNETCORE_HTTPS_PORT=8421
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Sara.Api.pfx
      - GOOGLE_APPLICATION_CREDENTIALS=/app/Files/brenda-wallet-firebase.json
    networks:
      - brenda-network
  carol:
    image: "carol"
    build:
      context: ./api
      dockerfile: Carol.Api/Dockerfile
    ports:
      - 8420:443
    volumes:
      - /c/Users/julol/.aspnet/https:/https
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Carol.Api.pfx
    networks:
      - brenda-network
  brenda:
    image: "brenda"
    build:
      context: ./api
      dockerfile: Brenda.Web/Dockerfile
    volumes:
      - /c/Users/julol/.aspnet/https:/https
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+
      - ASPNETCORE_HTTPS_PORT=44302
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Brenda.Web.pfx
    ports:
      - 44302:443
    networks:
      - brenda-network
  

networks:
  brenda-network:
    driver: bridge
    external: true
      
