name: brenda_wallet
description: Carteira Brenda

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.10+16

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  toast: ^0.1.5
  g_captcha: ^1.0.0
  flutter_masked_text: ^0.8.0
  qr_mobile_vision: ^1.0.1+1
  qr_flutter: ^3.2.0
  http: ^0.12.2
  sqflite: ^1.3.1
  geolocator: ^5.3.2+2
  permission_handler: ^5.0.1+1
  chewie: ^0.9.10
  video_player: ^0.10.11+2
  firebase_messaging: ^7.0.0
  intl: ^0.16.1
  wakelock: ^0.1.4+2
  device_info: ^0.4.2+7
  flutter_secure_storage: ^3.3.3
  webview_flutter: ^0.3.22+1
  receive_sharing_intent: ^1.4.1
  flutter_flavor: ^1.0.1+2
  share: ^0.6.5+2
  property_change_notifier: ^0.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
